title: 'Chiyo'
description: "My Personal Blog"
baseurl: "/"
url: "https://ch1y0w0.github.io"

header_pages:
  - index.md
  - whoami.md
  - contact.md

style: dark

footer: 'Follow me on <a href="https://x.com/ch1y0w0">X</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
